# -*- mode: ruby -*-
# vi: set ft=ruby :


# Ubuntu server image
IMAGE_NAME = "generic/ubuntu2004" 

# Run with noparallel by default
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.box = IMAGE_NAME

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
        v.gui = false
        v.network "private_network", ip: "172.16.3.10"
        # To change the default VirtualBox NAT subnet, uncomment the following line
        # v.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
    end

    config.vm.define "ubuntu20.04" do |ubuntu|
        ubuntu.vm.hostname = "ubuntu2004"
    end

end
